# Business Problem -  Predict the Price of Banglore House

## Using Linear Regression - Supervised Machine Learning Algorithm

#### Load Libraries 

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn 

In [3]:
# Data Should be of numeric

#### Load Data

In [5]:
df = pd.read_csv('C:/Users/Bhushan sharma/Desktop/DataTrained/Data_set/bangalore_house_prize.csv')
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [28]:
df.shape

(7120, 108)

In [29]:
y = df['price']

In [30]:
y.shape

(7120,)

In [31]:
x = df.drop('price', axis = 1)

In [32]:
x.shape

(7120, 107)

In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 42)

In [34]:
print('Shape of X_train', x_train.shape)
print('Shape of y_train', y_train.shape)
print('shape of x_test', x_test.shape)
print('shape of y_test', y_test.shape)

Shape of X_train (4984, 107)
Shape of y_train (4984,)
shape of x_test (2136, 107)
shape of y_test (2136,)


### Feature Scalling

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x)

x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

x_train.shape

(4984, 107)

## Linear Regression- ML learning Training

In [46]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [47]:
lr.coef_

array([ 3.07574328e+00,  3.14189987e-01,  7.43052133e+01, -1.34413002e+01,
        6.75526579e+01,  9.12359761e-01, -1.19517186e-01, -2.14121807e+00,
       -2.07184909e+00, -3.29605336e+00, -2.51732015e+00,  3.93500276e-01,
       -1.15678381e+00,  2.09868792e+00,  4.02810512e-01, -1.51163557e+00,
       -2.95473425e-01,  2.60096888e+00, -1.51204816e+00,  2.24281911e+00,
       -2.95585675e+00, -1.91248030e+00, -1.01540558e+00, -1.63285029e-01,
        1.18803939e+00,  2.12438369e+00, -5.43726020e+00, -8.37628474e-01,
       -6.63812708e-01,  1.90326511e+00, -4.09399827e-01, -5.52908187e-01,
        6.70764187e-01, -1.56750120e+00,  1.47386835e-01, -1.43827533e+00,
        4.26216477e-01,  7.03020032e-01,  3.50259644e+00,  1.51474393e-01,
        5.39254931e-01,  3.28297944e-01, -2.85325142e-01,  1.19354039e+00,
       -1.74991124e+00, -3.29000077e+00, -2.97797668e-01,  4.07293109e-02,
       -7.97453664e-01, -4.50689048e+00, -1.14424716e+00,  5.95286100e-01,
        1.01286701e+00, -

In [49]:
lr.intercept_

96.46388595343522

array([ 27.1255696 ,  54.92881604,  66.04471769, ...,  73.75589639,
        55.10884796, 203.47040961])

In [51]:
 lr.predict([x_test[0, :]])

array([27.1255696])

In [54]:
lr_predict = lr.predict(x_test)

In [55]:
lr_predict.shape

(2136,)

In [56]:
y_test.shape

(2136,)

In [57]:
lr.score(x_train, y_train)

0.8505254408371566

In [59]:
lr.score(x_test, y_test)

0.8658745757087329

In [60]:
#  For Checking performance

In [61]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [64]:
print('Mean_Squared_error', mean_squared_error(y_test, lr_pred))
print('Mean_absolute_error', mean_absolute_error(y_test, lr_pred))
print('Root mean squared Error', np.sqrt(mean_squared_error(y_test, lr_pred)))

Mean_Squared_error 1778.48297707038
Mean_absolute_error 17.674285111522668
Root mean squared Error 42.17206394131523


In [65]:
from sklearn.metrics import r2_score

In [67]:
print('r2_score: ', r2_score(y_test, lr_pred))

r2_score:  0.8658745757087329
